export const GET_CHARACTER = 'GET_CHARACTER';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
export const GET_CHARACTER_ID = 'GET_CHARACTER_ID';
export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';